import { describe, expect, it } from "vitest";
import { canAccessPath, canViewOrderFacture, hasAllAccess, hasPermission, isPublicPath, isRole, PERMISSIONS, satisfiesRoleGate } from "@/lib/auth/roles";
import { isValidPin } from "@/lib/auth/pin";

describe("authentication and authorization", () => {
  it("accepts a 4-6 digit PIN and rejects a wrong shape", () => {
    expect(isValidPin("1111")).toBe(true);
    expect(isValidPin("12")).toBe(false);
    expect(isValidPin("abcdef")).toBe(false);
  });

  it("keeps each role on its own screens", () => {
    expect(canAccessPath("MANAGER", "/manager/tables")).toBe(true);
    expect(canAccessPath("MANAGER", "/manager/products")).toBe(true);
    expect(canAccessPath("MANAGER", "/manager/inventory")).toBe(true);
    expect(canAccessPath("MANAGER", "/manager/reports")).toBe(true);
    expect(canAccessPath("ADMIN", "/manager/tables")).toBe(true);
    expect(canAccessPath("ADMIN", "/manager/products")).toBe(true);
    expect(canAccessPath("ADMIN", "/manager/inventory")).toBe(true);
    expect(canAccessPath("WAITER", "/manager/tables")).toBe(false);
    expect(canAccessPath("CASHIER", "/manager/tables")).toBe(false);
    expect(canAccessPath("CASHIER", "/manager/products")).toBe(false);
    expect(canAccessPath("WAITER", "/waiter/orders/new")).toBe(true);
    expect(canAccessPath("WAITER", "/cashier/bills")).toBe(false);
    expect(canAccessPath("CASHIER", "/cashier/outstanding")).toBe(true);
    expect(canAccessPath("CASHIER", "/admin/users")).toBe(false);
    expect(canAccessPath("WAITER", "/manager/orders")).toBe(false);
    expect(canAccessPath("MANAGER", "/manager/orders")).toBe(true);
    expect(canAccessPath("MANAGER", "/manager/inventory")).toBe(true);
    expect(canAccessPath("MANAGER", "/admin/settings")).toBe(false);
    expect(canAccessPath("ADMIN", "/admin")).toBe(true);
    expect(canAccessPath("ADMIN", "/admin/audit")).toBe(true);
    expect(canAccessPath("ADMIN", "/admin/")).toBe(true);
    expect(canAccessPath("ADMIN", "/cashier/bills")).toBe(true);
    expect(isPublicPath("/login")).toBe(true);
    expect(isPublicPath("/login/")).toBe(true);
    expect(isPublicPath("/manifest.webmanifest")).toBe(true);
    expect(isPublicPath("/admin")).toBe(false);
    expect(isRole("ADMIN")).toBe(true);
    expect(isRole("OWNER")).toBe(true);
    expect(isRole("admin")).toBe(false);
    expect(isRole("owner")).toBe(false);
  });

  it("gives OWNER every business path and permission without changing other roles", () => {
    expect(canAccessPath("OWNER", "/owner")).toBe(true);
    expect(canAccessPath("OWNER", "/waiter/orders/new")).toBe(true);
    expect(canAccessPath("OWNER", "/manager/tables")).toBe(true);
    expect(canAccessPath("OWNER", "/cashier/bills")).toBe(true);
    expect(canAccessPath("OWNER", "/cashier/outstanding")).toBe(true);
    expect(canAccessPath("OWNER", "/manager/products")).toBe(true);
    expect(canAccessPath("OWNER", "/manager/inventory")).toBe(true);
    expect(canAccessPath("OWNER", "/manager/purchases")).toBe(true);
    expect(canAccessPath("OWNER", "/manager/reports")).toBe(true);
    expect(canAccessPath("OWNER", "/manager/maison")).toBe(true);
    expect(canAccessPath("OWNER", "/admin/users")).toBe(true);
    expect(canAccessPath("OWNER", "/admin/settings")).toBe(true);
    expect(canAccessPath("OWNER", "/admin/audit")).toBe(true);
    expect(canAccessPath("OWNER", "/print/order/1")).toBe(true);

    expect(canAccessPath("ADMIN", "/waiter")).toBe(true);
    expect(canAccessPath("ADMIN", "/cashier/payments")).toBe(true);
    expect(canAccessPath("ADMIN", "/manager/orders")).toBe(true);
    expect(hasAllAccess("ADMIN")).toBe(true);
    expect(hasAllAccess("OWNER")).toBe(false);
    expect(hasAllAccess("MANAGER")).toBe(false);
    expect(canAccessPath("MANAGER", "/owner")).toBe(false);
    expect(canAccessPath("MANAGER", "/admin/users")).toBe(false);
    expect(canAccessPath("CASHIER", "/owner")).toBe(false);
    expect(canAccessPath("WAITER", "/owner")).toBe(false);
    expect(canAccessPath("WAITER", "/admin/users")).toBe(false);

    expect(satisfiesRoleGate("OWNER", ["WAITER"])).toBe(true);
    expect(satisfiesRoleGate("OWNER", ["CASHIER"])).toBe(true);
    expect(satisfiesRoleGate("OWNER", ["MANAGER"])).toBe(true);
    expect(satisfiesRoleGate("OWNER", ["ADMIN"])).toBe(true);
    expect(satisfiesRoleGate("ADMIN", ["OWNER"])).toBe(true);
    expect(satisfiesRoleGate("ADMIN", ["WAITER"])).toBe(true);
    expect(satisfiesRoleGate("ADMIN", ["CASHIER"])).toBe(true);
    expect(satisfiesRoleGate("MANAGER", ["OWNER"])).toBe(false);
    expect(satisfiesRoleGate("CASHIER", ["OWNER"])).toBe(false);
    expect(satisfiesRoleGate("WAITER", ["OWNER"])).toBe(false);
    expect(satisfiesRoleGate("ADMIN", ["ADMIN"])).toBe(true);
    expect(satisfiesRoleGate("WAITER", ["CASHIER"])).toBe(false);
  });

  it("blocks restricted operations by role", () => {
    expect(hasPermission("WAITER", "createOrder")).toBe(true);
    expect(hasPermission("WAITER", "recordPayment")).toBe(false);
    expect(hasPermission("CASHIER", "recordPayment")).toBe(true);
    expect(hasPermission("CASHIER", "payLater")).toBe(true);
    expect(hasPermission("CASHIER", "printFacture")).toBe(true);
    expect(hasPermission("CASHIER", "viewAllOrders")).toBe(true);
    expect(hasPermission("CASHIER", "createOrder")).toBe(false);
    expect(hasPermission("CASHIER", "manageProducts")).toBe(false);
    expect(hasPermission("CASHIER", "manageInventory")).toBe(false);
    expect(hasPermission("CASHIER", "manageMaison")).toBe(false);
    expect(hasPermission("WAITER", "manageMaison")).toBe(false);
    expect(hasPermission("CASHIER", "manageUsers")).toBe(false);
    expect(hasPermission("CASHIER", "manageSettings")).toBe(false);
    expect(hasPermission("MANAGER", "viewAllOrders")).toBe(true);
    expect(hasPermission("MANAGER", "manageProducts")).toBe(true);
    expect(hasPermission("MANAGER", "manageInventory")).toBe(true);
    expect(hasPermission("MANAGER", "viewReports")).toBe(true);
    expect(hasPermission("MANAGER", "manageMaison")).toBe(true);
    expect(hasPermission("MANAGER", "recordPayment")).toBe(false);
    expect(hasPermission("MANAGER", "payLater")).toBe(false);
    expect(hasPermission("MANAGER", "createOrder")).toBe(false);
    expect(hasPermission("WAITER", "viewAllOrders")).toBe(false);
    expect(hasPermission("WAITER", "viewOwnOrders")).toBe(true);
    expect(hasPermission("ADMIN", "manageUsers")).toBe(true);
    expect(hasPermission("ADMIN", "manageProducts")).toBe(true);
    expect(hasPermission("ADMIN", "manageInventory")).toBe(true);
    expect(hasPermission("WAITER", "manageProducts")).toBe(false);
    expect(hasPermission("ADMIN", "manageSettings")).toBe(true);
    expect(hasPermission("ADMIN", "manageMaison")).toBe(true);
    expect(hasPermission("ADMIN", "viewAudit")).toBe(true);
    expect(hasPermission("ADMIN", "recordPayment")).toBe(true);
    expect(hasPermission("WAITER", "manageUsers")).toBe(false);
    expect(hasPermission("WAITER", "manageSettings")).toBe(false);
    expect(hasPermission("CASHIER", "manageUsers")).toBe(false);
    expect(hasPermission("CASHIER", "manageSettings")).toBe(false);
    expect(hasPermission("MANAGER", "manageUsers")).toBe(false);
    expect(hasPermission("MANAGER", "manageSettings")).toBe(false);
    expect(hasPermission("MANAGER", "viewAudit")).toBe(false);
    expect(hasPermission("OWNER", "createOrder")).toBe(true);
    expect(hasPermission("OWNER", "recordPayment")).toBe(true);
    expect(hasPermission("OWNER", "payLater")).toBe(true);
    expect(hasPermission("OWNER", "printFacture")).toBe(true);
    expect(hasPermission("OWNER", "manageProducts")).toBe(true);
    expect(hasPermission("OWNER", "manageInventory")).toBe(true);
    expect(hasPermission("OWNER", "viewReports")).toBe(true);
    expect(hasPermission("OWNER", "manageMaison")).toBe(true);
    expect(hasPermission("OWNER", "manageUsers")).toBe(true);
    expect(hasPermission("OWNER", "manageSettings")).toBe(true);
    expect(hasPermission("OWNER", "viewAudit")).toBe(true);
    expect(hasPermission("OWNER", "purgeBusinessData")).toBe(true);
    expect(hasPermission("ADMIN", "purgeBusinessData")).toBe(true);
    expect(hasPermission("WAITER", "purgeBusinessData")).toBe(false);
    expect(hasPermission("CASHIER", "purgeBusinessData")).toBe(false);
    expect(hasPermission("MANAGER", "purgeBusinessData")).toBe(false);
    expect(hasPermission("ADMIN", "createOrder")).toBe(true);
    expect(PERMISSIONS.every((permission) => hasPermission("ADMIN", permission))).toBe(true);
    expect(hasPermission("MANAGER", "manageUsers")).toBe(false);
    expect(PERMISSIONS.every((permission) => hasPermission("OWNER", permission))).toBe(true);
  });
});
