export const KITCHEN_STORES_CATEGORY = "Kitchen Stores";

export type KitchenBaseUnitCode = "KG" | "PIECE" | "L";

/** Ingredients and kitchen supplies. Not sold on POS. Counted in whole kg / pieces / litres. */
export const KITCHEN_BASE_MATERIALS: { name: string; baseUnitCode: KitchenBaseUnitCode }[] = [
  { name: "Chicken", baseUnitCode: "KG" },
  { name: "Beef", baseUnitCode: "KG" },
  { name: "Goat", baseUnitCode: "KG" },
  { name: "Pork", baseUnitCode: "KG" },
  { name: "Fish Tilapia", baseUnitCode: "KG" },
  { name: "Captain Fish", baseUnitCode: "KG" },
  { name: "Rabbit", baseUnitCode: "KG" },
  { name: "Sausage", baseUnitCode: "KG" },
  { name: "Tuna", baseUnitCode: "KG" },
  { name: "Eggs", baseUnitCode: "PIECE" },
  { name: "Rice", baseUnitCode: "KG" },
  { name: "Pasta", baseUnitCode: "KG" },
  { name: "Potatoes", baseUnitCode: "KG" },
  { name: "Plantain", baseUnitCode: "KG" },
  { name: "Green Banana", baseUnitCode: "KG" },
  { name: "Maize Flour", baseUnitCode: "KG" },
  { name: "Wheat Flour", baseUnitCode: "KG" },
  { name: "Bread", baseUnitCode: "PIECE" },
  { name: "Burger Buns", baseUnitCode: "PIECE" },
  { name: "Onions", baseUnitCode: "KG" },
  { name: "Tomatoes", baseUnitCode: "KG" },
  { name: "Garlic", baseUnitCode: "KG" },
  { name: "Ginger", baseUnitCode: "KG" },
  { name: "Mixed Vegetables", baseUnitCode: "KG" },
  { name: "Mushrooms", baseUnitCode: "KG" },
  { name: "Cabbage", baseUnitCode: "KG" },
  { name: "Carrots", baseUnitCode: "KG" },
  { name: "Salad Leaves", baseUnitCode: "KG" },
  { name: "Avocado", baseUnitCode: "PIECE" },
  { name: "Lemon", baseUnitCode: "PIECE" },
  { name: "Peppers", baseUnitCode: "KG" },
  { name: "Cooking Oil", baseUnitCode: "L" },
  { name: "Charcoal", baseUnitCode: "KG" },
  { name: "Milk", baseUnitCode: "L" },
  { name: "Cheese", baseUnitCode: "KG" },
  { name: "Butter", baseUnitCode: "KG" },
  { name: "Mayonnaise", baseUnitCode: "L" },
  { name: "Tomato Sauce", baseUnitCode: "L" },
  { name: "Salt", baseUnitCode: "KG" },
  { name: "Sugar", baseUnitCode: "KG" },
  { name: "Cooking Spices", baseUnitCode: "KG" },
];
